name: AndroidBuild
on:

  pull_request:
    branches: [ main ]

  push:
    branches: [ main , Configure-GitHub-Actions-with-lint]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.5


      - name: Setup Java JDK
        uses: actions/setup-java@v4.2.1
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: Make gradlew executable
        run: chmod +x ./gradlew
      - name: Build with gradle
        run: ./gradlew build

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v4.3.3
        with:
          name: CurrencyConverter.apk
          path: app/build/outputs/apk/debug/app-debug.apk
